name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please search existing issues before filing a new one.

  - type: input
    id: version
    attributes:
      label: AIShield Version
      description: What version of AIShield are you running?
      placeholder: "e.g., 0.2.0 or commit SHA"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "e.g., rustc 1.75.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command That Failed
      description: The exact command you ran (sanitize sensitive info)
      placeholder: |
        cargo run -p aishield-cli -- scan /path/to/project
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, I saw..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Steps to reproduce the behavior. Include minimal code sample if possible.
      placeholder: |
        1. Create file test.py with content: ...
        2. Run: cargo run -p aishield-cli -- scan test.py
        3. Observe: ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or stack traces (if applicable)
      render: text

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (other)
        - Windows (WSL)
        - Windows (native)
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided a minimal reproduction
          required: true
        - label: I am using the latest version
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
