name: ✨ Feature Request
description: Suggest an enhancement or new feature
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        
        Please search existing feature requests before filing a new one.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I would like AIShield to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: "I could work around this by..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case or workflow
      placeholder: |
        I'm using AIShield in CI/CD for...
        I need this feature because...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New detection rule/pattern
        - CLI enhancement
        - Output format improvement
        - Integration (CI/Editor)
        - Dashboard/Analytics
        - Performance improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my workflow)
        - High (significant impact)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: How are you currently working around this limitation?
      placeholder: "Currently I..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to implement this feature myself
        - label: I can help test this feature
        - label: I can provide more details if needed

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or any other context
